management:
  server:
    port: 50000
  endpoints:
    web:
      exposure:
        include: prometheus, health
      base-path: "/"
  endpoint:
    metrics:
      enabled: true
    prometheus:
      enabled: true

    health:
      enabled: false
      show-details: "ALWAYS"
      db:
        enabled: false
server:
  port: 4001
  servlet:
    context-path: ""
spring:
  application:
    name: student-management-service
  main:
    allow-bean-definition-overriding: true
  profiles:
    active: ${ENVIRONMENT:dev}
  jpa:
    hibernate:
      ddl-auto: update
---
spring:
  config:
    activate:
      on-profile: dev
  elasticsearch:
    rest:
      uris: ${LOS_ELASTIC_URL:172.50.3.71}:9200
  liquibase:
    change-log: classpath:db/changelog-master.yml
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: ${DATABASE_URL:jdbc:mysql://localhost:3306/student?zeroDateTimeBehavior=convertToNull}
    username: ${LOS_DATABASE_USERNAME:root}
    password: ${LOS_DATABASE_PASSWORD:root}
